"""
Gordon Reid "Synth Secrets" Chapter 47: Practical Bowed-String Synthesis
Agent Gamma-W (Winds/Strings/Brass) Translation

Acoustic Principle:
A violin body is essentially a complex filter bank with prominent formants (resonances) around 
300Hz, 700Hz, and 3kHz. The raw sawtooth generated by the bridge must be passed through these 
resonances to sound authentic.

S-1 Hardware Translation:
1. Since the S-1 does not have parallel resonant bandpass filters, we must use its single low-pass 
   filter to emphasize the most critical lower-mid body resonance (around 700Hz).
2. Pure Sawtooth core (CC 20).
3. Filter Cutoff (CC 74) is tuned to roughly the "700Hz" range (MIDI ~70) with a moderate 
   Resonance (CC 71) bump to simulate the wooden body cavity.
4. "Singing" ADSR envelope: Slow attack (CC 73), full sustain (CC 70), and moderate release (CC 72).
5. Delayed vibrato (CC 17) generated via continuous CC updates in the sequencer.

Taxonomic Application:
[Origin: Bow/Friction] + [Behavior: Evolving] + [Emotion: Tension] + [Stress: Safe-Mode] + [Role: Lead] + [Historical: Acoustic-Emulation]
"""

import time
from server.kernel.s1_midi import Midi, CC

def run_bowed_strings_1_patch():
    print("Agent Gamma-W: Initializing Bowed Strings 1 (Ch 47) Patch...")
    s1 = Midi()
    
    # Base Oscillator: Pure Sawtooth
    s1.cc(CC.SAW_LEVEL, 127)
    s1.cc(CC.OSC_SQUARE, 0)
    s1.cc(CC.SUB_LEVEL, 0)
    s1.cc(CC.NOISE_LEVEL, 0)
    
    # Filter: Single resonant peak simulating the main body formant (~700Hz)
    s1.cc(CC.FILTER_CUTOFF, 68) 
    s1.cc(CC.FILTER_RES, 45)    # Prominent resonance to simulate wooden body
    s1.cc(CC.FILTER_ENV, 0)
    s1.cc(CC.FILTER_LFO, 0)
    
    # Envelope: Singing envelope with bowing attack
    s1.cc(CC.AMP_ATTACK, 40)
    s1.cc(CC.AMP_DECAY, 0)
    s1.cc(CC.AMP_SUSTAIN, 127)
    s1.cc(CC.AMP_RELEASE, 55)
    
    # LFO Pitch Modulation: Prepared for manual delayed injection
    s1.cc(CC.LFO_MODE, 0)
    s1.cc(CC.LFO_SHAPE, 1)      # Triangle
    s1.cc(CC.LFO_RATE, 70)      # Slightly faster vibrato
    s1.cc(CC.PITCH, 0)          
    
    # Effects: Reverb to simulate acoustic space
    s1.cc(CC.CHORUS_LEVEL, 0)
    s1.cc(CC.REVERB_LEVEL, 80)
    s1.cc(CC.DELAY_LEVEL, 0)
    
    print("Patch initialized. Playing test sequence...")
    
    notes = [60, 62, 65, 64]
    
    for note in notes:
        s1.on(note, velocity=85)
        
        # Attack phase without vibrato
        s1.cc(CC.PITCH, 0)
        time.sleep(0.4)
        
        # Inject vibrato during sustain
        for depth in range(1, 12, 1):
            s1.cc(CC.PITCH, depth)
            time.sleep(0.05)
        
        time.sleep(1.0) # Hold with vibrato
        
        s1.off(note)
        s1.cc(CC.PITCH, 0) # Clear vibrato for next note
        time.sleep(0.2)

    print("Bowed Strings 1 sequence complete.")

if __name__ == "__main__":
    run_bowed_strings_1_patch()
